config/routes.rb
Rails.application.routes.draw do

  

  resources :products
get 'auth/:provider/callback', to: 'users#facebook'
namespace :api do 
  resources :users, except: [:new, :edit]
end
  resources :users do 
  	collection do 
       get 'sign_in'
       post 'signup'
       delete 'logout'
       get 'forget_password'
       post 'recover_password'
  	end
  end
  resources :carts do 
    collection do 
      get 'add_to_cart'
    end
  end
  root to: "products#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/artical.rb
class Artical < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/cricket.rb
class Cricket < Sport
  
end

app/models/football.rb
class Football < Sport
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>", small: "200x200>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	belongs_to :user
	belongs_to :product
end

app/models/jai.rb
class Jai < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :images
end

app/models/roja.rb
class Roja < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/roles_user.rb
class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	validates :password , presence: true
	validates :confirm_password , presence: true
	validates :mobile, presence: true, numericality: true
  has_one :image 
  has_and_belongs_to_many :roles
  accepts_nested_attributes_for :image
    before_save :encrypt_password
    before_save :check_name
    before_validation :verify_password
#scope :admin?, -> {true if self.email == "admin@gmail.com"}
  def admin?
     self.roles.pluck(:name).include?("admin")
  end
def check_name
  if name.blank?
    self.name="unknow"
  end
end

def self.omniauth(auth)
    #where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
     where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      byebug
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.profile_image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save(validate: false)
    end
  end

    def encrypt_password
      unless password.nil?
       self.password = Digest::MD5.hexdigest(password)
       self.confirm_password = Digest::MD5.hexdigest(confirm_password)
      end 
    end
    def verify_password
      unless password.nil? 
     	  if password != confirm_password
             errors.add(:base, "password & confirm_password are not equal!" )
    	  end
      end
    end
	def self.authenticate(email, password)
		if @user = User.where(email: email, password: Digest::MD5.hexdigest(password)).last
           @user
       else
       	nil
       end
	end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	def index
       @users = User.all
       respond_to do | format |
        format.json {render json: @users}
       end
	end
	def create
      @user = User.new(user_params)
      respond_to do | format |
        if @user.save
           format.json {render json: @user}
       else
       	   format.json {render json: @user.errors}
        end
      end
	end

  def destroy 
     @user = User.find params[:id]
     respond_to do | format |
       @user.destroy 
        format.json {render json: "Deleted successfully\n"}
      end
     # redirect_to users_path
    end
#def edit
 #   @user = User.find params[:id]
  # format.json {render json: @user}
  #end
#end

  def update
    @user = User.find params[:id]
    respond_to do | format |
    if @user.update(user_params)
      format.json {render json: "updated sucessfully \n"}
       #redirect_to users_path
       else
       render :edit
       format.json {render json: @user} 
    end
  end 
end
  private
  def user_params
	  params.require(:user).permit!
	end
end


#what is params .
# a strong hash in rails created 
#from HashWithIndifferentAccess class , which stores 
#all the data's in key and value pair. 
# params = {user: 
# 	{name: "ABC", email: "abc@gmail.com"}, 
# 	extra_columns_will_be_there: 'value', permitted: false
# }


# params.require(:user).permit!

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:sign_in, :signup, :new, :create, :facebook, :forget_password, :recover_password]
   include MoveFromSessionToCart
  def index
  	@users =  User.all
   # authorize! :manage, @users
  end

  def new
  	@user = User.new
    @user.build_image
  end
  def create 
  	@user = User.new(user_params)
  	if @user.save(validate: false)
       #SendEmailMailer.welcome(@user).deliver_now!
       redirect_to users_path
   else
   	render :new
  	end
  end
  def facebook
    user = User.omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to products_path

  end
  def edit
    @user = User.find params[:id]
  end
  def update
     @user = User.find params[:id]
    # authorize! :update, @user
    if @user.update(user_params)
       redirect_to users_path
       else
       render :edit 
    end
    
  end 
  def show
    @user = User.find params[:id]
  end
  def destroy 
     @user = User.find params[:id]
     @user.destroy
     redirect_to users_path
  end
  def signup
      @user = User.authenticate(params[:email], params[:password])
      if @user
          session[:user_id] = @user.id
          add_items_to_cart(@user)
          flash[:notice] = "Successfully logged in!"
          #redirect_to user_path(@user)
          redirect_to products_path
        else
          flash[:notice] = "Either email or password is wrong!"
          redirect_to sign_in_users_path
      end
  end
  def logout
    session[:user_id] = nil
    redirect_to sign_in_users_path
  end
  def recover_password
    @user = User.where(email: params[:email]).last
    if @user
        @user.update({password: params[:password], confirm_password: params[:confirm_password]})
        flash[:notice] = "New password has been set Successfully, ty login!"
         redirect_to root_path
       else
        flash[:notice] = "User not found with given email id"
        redirect_to root_path
    end
  end
  private 
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/abcd_helper.rb
module AbcdHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/guru_helper.rb
module GuruHelper
end

app/helpers/india_helper.rb
module IndiaHelper
end

app/helpers/muttu_helper.rb
module MuttuHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/forget_password.html.erb
<%= form_tag action: :recover_password, method: :post do%>
<table class='table'>
<tr>
<td><%= label_tag :email%></td>
<td><%= text_field_tag :email%></td>
</tr>
<tr>
<td><%= label_tag :password%></td>
<td><%= password_field_tag :password%></td>
</tr>
<tr>
<td><%= label_tag :confirm_password%></td>
<td><%= password_field_tag :confirm_password%></td>
</tr>
<tr>
<td><%= submit_tag %></td>
</tr>
</table> 
<%end%>

app/views/users/index.html.erb
<!--%= @users.inspect %-->
<div class="container">
<table class="table table-striped">
	<tr>
	    <th>Image</th>
		<th>Name</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Status</th>
		</tr>
<% @users.each do | i | %>
	<tr>  
	  <td><%= image_tag i.image.photo(:thumb) unless i.image.blank?%> </td>
      <td><%= i.name %></td>
      <td><%= i.email %></td>
      <td><%= i.mobile %></td>
      <td><%= i.status %></td>
      <td><%= link_to "Show", user_path(i), :class=>"btn btn-success"%></td>
      <% if can? :update, i %>
      <td><%= link_to "Edit", edit_user_path(i)%></td>
      <td><%= link_to "Delete", i, method: :delete, data: {confirm: "Are you sure!"}, :class=>"btn btn-danger"%></td>
	</tr>
	<%end%>
<%end%>
</table>

<%= link_to "Add New User", new_user_path%>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
<% if @user.errors.any? %>
  <% @user.errors.messages.each do |key,msg |%>
    <ul>
    <li><%= "#{key} : " + msg.first%></li>
    </ul>
  <%end%>
<%end%>
<table  class="table table-striped">
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :email%></td>
  <td><%= f.email_field :email%></td>
  </tr>
  <tr>
  <td><%= f.label :password%></td>
  <td><%= f.password_field :password%></td>
  </tr>
  <tr>
  <td><%= f.label :confirm_password%></td>
  <td><%= f.password_field :confirm_password%></td>
  </tr>
  <tr>
  <td><%= f.label :mobile%></td>
  <td><%= f.text_field :mobile%></td>
  </tr>
  <tr>
  <td><%= f.label :status%></td>
  <td><%= f.check_box :status%></td>
  </tr>
  <%= f.fields_for :image do | image |%>
     <tr>
     <td><%= image.label :photo%></td>
     <td><%= image.file_field :photo%></td>
     </tr>
  <%end%>
    <tr>
  <td><%= f.submit "SignUp"%></td>
  </tr>
</table>
<%end%>

<%= link_to "<<back", users_path%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/sign_in.html.erb
<%= form_tag action: :signup, method: :post do%>
<table  class="table table-striped">
  <tr>
  <td><%= label_tag :email%></td>
  <td><%= email_field_tag :email%></td>
  </tr>
  <tr>
  <td><%= label_tag :password%></td>
  <td><%= password_field_tag :password%></td>
  </tr>
   <tr>
  <td><%= submit_tag "SignIn"%></td>
  <td><%= link_to "SignUp", new_user_path%></td>
   <td><%= link_to "Recover Password", forget_password_users_path%></td>
  <td><%= link_to "Facebook+", "/auth/facebook"%></td>
  </tr>
  <p></p>
</table>
<%end%>