config/routes.rb
Rails.application.routes.draw do

  

  resources :products
get 'auth/:provider/callback', to: 'users#facebook'
namespace :api do 
  resources :users, except: [:new, :edit]
end
  resources :users do 
  	collection do 
       get 'sign_in'
       post 'signup'
       delete 'logout'
       get 'forget_password'
       post 'recover_password'
  	end
  end
  resources :carts do 
    collection do 
      get 'add_to_cart'
    end
  end
  root to: "products#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/artical.rb
class Artical < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/cricket.rb
class Cricket < Sport
  
end

app/models/football.rb
class Football < Sport
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>", small: "200x200>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	belongs_to :user
	belongs_to :product
end

app/models/jai.rb
class Jai < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :images
end

app/models/roja.rb
class Roja < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/roles_user.rb
class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	validates :password , presence: true
	validates :confirm_password , presence: true
	validates :mobile, presence: true, numericality: true
  has_one :image 
  has_and_belongs_to_many :roles
  accepts_nested_attributes_for :image
    before_save :encrypt_password
    before_save :check_name
    before_validation :verify_password
#scope :admin?, -> {true if self.email == "admin@gmail.com"}
  def admin?
     self.roles.pluck(:name).include?("admin")
  end
def check_name
  if name.blank?
    self.name="unknow"
  end
end

def self.omniauth(auth)
    #where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
     where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      byebug
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.profile_image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save(validate: false)
    end
  end

    def encrypt_password
      unless password.nil?
       self.password = Digest::MD5.hexdigest(password)
       self.confirm_password = Digest::MD5.hexdigest(confirm_password)
      end 
    end
    def verify_password
      unless password.nil? 
     	  if password != confirm_password
             errors.add(:base, "password & confirm_password are not equal!" )
    	  end
      end
    end
	def self.authenticate(email, password)
		if @user = User.where(email: email, password: Digest::MD5.hexdigest(password)).last
           @user
       else
       	nil
       end
	end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def name
  end

  def brand
  end

  def item
  end

  def size
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user, only: [:index]
  def index
  	@product = Product.all
  end

  def new
  	@product = Product.new
  end
  def create
  	 image_attributes = product_params[:image]["photo"]
     product_params.delete(:image)
     @product = Product.new(product_params)
     if @product.save
        image_attributes.each do |each_image|
          image = Image.new(photo: each_image, product: @product)
          image.save(validate: false)
        end
        redirect_to products_path
        else
          render :new
     end
  end
  def edit
  end

  def show
  end

  private
  def product_params
  	params.require(:product).permit!
  end
end

app/helpers/abcd_helper.rb
module AbcdHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/guru_helper.rb
module GuruHelper
end

app/helpers/india_helper.rb
module IndiaHelper
end

app/helpers/muttu_helper.rb
module MuttuHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def user_signed_in?
		unless session[:user_id].blank?
			true 
		else
			false
		end
	end
end

app/views/product/brand.html.erb
<h1>Product#brand</h1>
<p>Find me in app/views/product/brand.html.erb</p>

app/views/product/item.html.erb
<h1>Product#item</h1>
<p>Find me in app/views/product/item.html.erb</p>

app/views/product/name.html.erb
<h1>Product#name</h1>
<p>Find me in app/views/product/name.html.erb</p>

app/views/product/size.html.erb
<h1>Product#size</h1>
<p>Find me in app/views/product/size.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<% if user_signed_in?%>
  |<%= link_to "Add Product", new_product_path if can? :create, @products %>
<%end%>
<% if current_user %>
<% cart_itmes_count = Cart.where(user: current_user).count%>
<p><%= link_to "items added to cart : #{cart_itmes_count}", carts_path%></p>
<%else%>
<p align = "right"><%= link_to "items added to cart : #{session[:cart_items].nil? ? 0 : session[:cart_items].count}", carts_path%></p>
<%end%>
<!--%= @users.inspect %-->
<div class="container">
<table class="table table-striped">
	<tr>
	    <th>Images</th>
		<th>Name</th>
		<th>Brand</th>
		<th>Price</th>
		<th>Size</th>
		</tr>
<% @product.each do | i | %>
	<tr>  
	  <td>
	  <% unless i.images.blank? %>
	    <% i.images.each do | image |%>
          <%= image_tag image.photo(:thumb)%>
	    <%end%>
	  <%end%>
	  </td>
      <td><%= i.name %></td>
      <td><%= i.brand %></td>
      <td><%= i.prize %></td>
      <td><%= i.size %></td>
      <td><%= link_to "+cart", add_to_cart_carts_path(product_id: i.id)%></td>
<%end%>
</table>
</div>

app/views/products/new.html.erb
<%= form_for @product do |f|%>
<% if @product.errors.any? %>
  <% @product.errors.messages.each do |key,msg |%>
    <ul>
    <li><%= "#{key} : " + msg.first%></li>
    </ul>
  <%end%>
<%end%>
<table  class="table table-striped">
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :brand%></td>
  <td><%= f.text_field :brand%></td>
  </tr>
  <tr>
  <td><%= f.label :prize%></td>
  <td><%= f.text_field :prize%></td>
  </tr>
  <tr>
  <td><%= f.label :size%></td>
  <td><%= f.select :size, %w(S M L XS XM XL )%></td>
  </tr>
  <%= f.fields_for :image do | image |%>
     <tr>
     <td><%= image.label :photo%></td>
     <td><%= image.file_field :photo, multiple: true%></td>
     </tr>
  <%end%>
    <tr>
  <td><%= f.submit "Add Product"%></td>
  </tr>
</table>
<%end%>

<%= link_to "<<back", products_path%>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>